#!/usr/bin/env python

"""
Booking system backend

TODO
  - use objects to manage each database table (room, bed, feature...)
  - pretty print rows in the "show" command
"""

__author__  = "Frederic Culot"
__version__ = "20150625"
__licence__ = "BSD"


import logging as log
import traceback

from cmdline import CmdLine
from processing import Processing


def main():
    cmdline = CmdLine()
    if cmdline.command:
        getattr(Processing(), "command_" + cmdline.command)(cmdline.options)


if __name__ == '__main__':
    try:
        log.basicConfig(level=log.DEBUG,
                        format='%(asctime)s %(levelname)-8s %(message)s',
                        datefmt='%m-%d %H:%M',
                        filename='book.log')
        main()
    except SystemExit:
        pass
    except Exception, e:
        log.exception(e)
        traceback.print_exc()
